### ISSUE TITLE
complex_test fails in Ubuntu 18.04 (64bit)

### ISSUE THREAD

**Issue by LordAro** [jwhitham/x86determiniser#2]
```
 $ make PLATFORM=linux64 -C tests/complex_test/
make: Entering directory '/home/cpigott/rvs/tools/x86determiniser/tests/complex_test'
../../bin/x64determiniser --branch-trace ctest.linux64.trace ctest.linux64
ctest.linux64: relocation error: ctest.linux64: symbol __get_cpu_features version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
AWAIT_FIRST_STAGE: child process exited immediately
Makefile:13: recipe for target 'ctest.linux64.ok' failed
make: *** [ctest.linux64.ok] Error 2
make: Leaving directory '/home/cpigott/rvs/tools/x86determiniser/tests/complex_test'
```

Some googling points to to the fact that libm.a is statically linked into the binary, which causes incompatibility (https://github.com/COMBINE-lab/salmon/issues/290).

Some experimentation shows that the test is consistent if you build the binary using `-lm` instead of statically linking - build it on RHEL6, and the test still passes on Ubuntu 18.04

It'd be nice if you could remove the need for checking the binary into the repo at all, but apparently that breaks things - the output from the binaries is different enough that the reference files are useless

**Comment by jwhitham** [comment]
That test needs a rethink. The 64-bit version is failing for me as well now, even with the same Linux environment. I have upgraded the PC since I worked on this, and the test program is now using __sin_avx instead of __sin_sse2. I'll see what can be done.

**Comment by jwhitham** [comment]
This test has been redesigned in version 2.1. I have precompiled the C modules to assembly, so that the the assembly files are checked in, and there is no binary. The same assembly code is used on Windows and Linux.
