### ISSUE TITLE
Fails to load DLL names when running in Docker on Windows

### ISSUE THREAD

**Issue by AJDurant** [jwhitham/x86determiniser#3]
When running x86determiniser in Docker on Windows the LoadDll info structure has null handles for most DLLs, leading https://github.com/jwhitham/x86determiniser/blob/c0259518ee47ed7b398185f7ac7eb23ffb184a47/src/loader/win/win_loader.c#L698 to return empty. Because of this, kernel32.dll is never seen so x86determiniser exits.

The null return is reported here: https://github.com/moby/moby/issues/37744 but unclear if this is actually where the problem lies.

It might be possible to load a module name using [GetModuleFileNameEx](https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulefilenameexa) with the child process. Or though enumeration of all the modules of the child process: https://learn.microsoft.com/en-us/windows/win32/psapi/enumerating-all-modules-for-a-process

Output from running the test:
```
# bin/x86determiniser.exe --debug --branch-trace tests/complex_test/ctest.win32.raw_trace tests/complex_test/ctest.win32.exe
INITIAL: library is 'C:\msys64\tmp\x8dE7DE.tmp.x86determiniser-1256.dll'
[tests/complex_test/ctest.win32.exe]
[[tests/complex_test/ctest.win32.exe]]
INITIAL: startAddress = 004014E0
AWAIT_FIRST: debug event 6
AWAIT_FIRST: load DLL = \\?\C:\Windows\SysWOW64\ntdll.dll base = 77AD0000
AWAIT_FIRST: debug event 6
AWAIT_FIRST: load DLL =  base = 76340000
AWAIT_FIRST: debug event 6
AWAIT_FIRST: load DLL =  base = 758E0000
AWAIT_FIRST: debug event 6
AWAIT_FIRST: load DLL =  base = 77210000
AWAIT_FIRST: debug event 2
AWAIT_FIRST: New thread 00000138
AWAIT_FIRST: debug event 1
AWAIT_FIRST: exception code 80000003
AWAIT_FIRST: debug event 1
AWAIT_FIRST: exception code 80000003
REMOTE_LOADER: don't know the kernel32.dll base address
```

adding in some debug:
```
# bin/x86determiniser.exe --debug --branch-trace tests/complex_test/ctest.win32.raw_trace tests/complex_test/ctest.win32.exe
INITIAL: library is 'C:\msys64\tmp\x8d58DC.tmp.x86determiniser-1716.dll'
[tests/complex_test/ctest.win32.exe]
[[tests/complex_test/ctest.win32.exe]]
INITIAL: startAddress = 004014E0
AWAIT_FIRST: debug event 6
AWAIT_FIRST: load DLL = \\?\C:\Windows\SysWOW64\ntdll.dll base = 77AD0000
AWAIT_FIRST: debug event 6
Unable get dll name for handle '00000000': Windows error code 0x6: The handle is invalid.
AWAIT_FIRST: load DLL =  base = 76340000
AWAIT_FIRST: debug event 6
Unable get dll name for handle '00000000': Windows error code 0x6: The handle is invalid.
AWAIT_FIRST: load DLL =  base = 758E0000
AWAIT_FIRST: debug event 6
Unable get dll name for handle '00000000': Windows error code 0x6: The handle is invalid.
AWAIT_FIRST: load DLL =  base = 77210000
AWAIT_FIRST: debug event 2
AWAIT_FIRST: New thread 00000138
AWAIT_FIRST: debug event 1
AWAIT_FIRST: exception code 80000003
AWAIT_FIRST: debug event 1
AWAIT_FIRST: exception code 80000003
REMOTE_LOADER: don't know the kernel32.dll base address
```

**Comment by jwhitham** [comment]
Hi Andy

Thank you for your bug report. 

GetModuleFileNameEx seems to require HMODULE which I think isn't available, though as you suggest, EnumProcessModules could find it. I think this ought to work, but I'm hesitant to try to fix this without being able to reproduce the problem.

I don't know much about Docker. I found that Docker for Windows has two backends, Hyper-V and WSL2 - which are you using?

It seems that neither is easy to install: Hyper-V requires a Windows upgrade, while WSL2 requires installing the WSL2 subsystem. I am curious about how the WSL2 backend actually works, and wonder if it is really using the Windows API, or something like Wine, which might account for the difference in the debug API behaviour. Does that seem plausible?

Does the same problem apply to x64determiniser too? (i.e. is it a WOW64 issue?)

Hope you are doing ok

Jack

**Comment by AJDurant** [comment]
I'll have a look at implementing an enumeration fix, as it's much easier for me to test.

> I don't know much about Docker. I found that Docker for Windows has two backends, Hyper-V and WSL2 - which are you using?

This is actually using neither. WSL2 is for linux containers on Windows, which doesn't have the issue as it's Linux, WSL2 itself uses Hyper-V with some extras to provide the virtualisation base (WSL1 did some fancy Wine like translation of syscalls). Hyper-V provides a VM infrastructure for the windows kernel. But in my case I'm using process isolation, which shares the kernel with the host system.

It's not a WOW64 issue, as it happens on both, though I get seperate errors trying to compile the x64 tests anyway.

**Comment by jwhitham** [comment]
Thanks Andy. This looks fine and I have merged it into master. I was able to test it by forcing the new "if" condition to True.

I couldn't resist doing some refactoring to avoid code duplication. The resulting code seems to be working but do let me know if you have problems with it. I'll make version 2.2 tag in a few days time.
